<a href="https://colab.research.google.com/github/345lakshayaggarwal-prog/EDA-Using-Python/blob/main/Task_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
# Load data
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/products.csv")

In [4]:
# Data Ingestion
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Index         1000 non-null   int64
 1   Name          1000 non-null   object
 2   Description   1000 non-null   object
 3   Brand         1000 non-null   object
 4   Category      1000 non-null   object
 5   Price         1000 non-null   int64
 6   Currency      1000 non-null   object
 7   Stock         1000 non-null   int64
 8   EAN           1000 non-null   int64
 9   Color         1000 non-null   object
 10  Size          1000 non-null   object
 11  Availability  1000 non-null   object
 12  Internal ID   1000 non-null   int64
dtypes: int64(5), object(8)
memory usage: 101.7+ KB

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
0,1,Thermostat Drone Heater,Consumer approach woman us those star.,Bradford-Yu,Kitchen Appliances,74,USD,139,8619793560985,Orchid,Medium,backorder,38
1,2,Ultra Speaker Iron Grill Advanced One,Point suggest easy money operation could white.,Douglas Group,Fitness Equipment,510,USD,351,3057216124300,MediumSeaGreen,Small,backorder,27
2,3,Watch Headphones Kettle,Reach husband education.,Landry-Austin,Beauty & Personal Care,254,USD,409,9825254410556,Lavender,XXL,pre_order,2
3,4,Portable Toaster Clock Monitor Silent,Always choose school poor table main.,"Odom, Norton and Foster",Makeup,69,USD,119,9490814777808,Pink,XL,in_stock,94
4,5,Pro Toaster Oven,Worry put discuss easy back too career.,"Fowler, Mendoza and Mcdaniel",Automotive,525,USD,727,4726650403799,LightCoral,XL,in_stock,95

In [5]:
# Check for duplicate rows
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [6]:
# Count duplicate rows
print("Number of duplicates:", df.duplicated().sum())

Number of duplicates: 0

In [7]:
# Drop duplicate rows
df_no_dup = df.drop_duplicates()

In [8]:
# drop irrelevant columns
df.drop(columns=['Index']),

(                                       Name  \
 0                   Thermostat Drone Heater
 1     Ultra Speaker Iron Grill Advanced One
 2                   Watch Headphones Kettle
 3     Portable Toaster Clock Monitor Silent
 4                          Pro Toaster Oven
 ..                                      ...
 995  Silent Router Phone Portable Automatic
 996              Digital Treadmill Clean Go
 997                  Wireless Vacuum Shaver
 998  Portable Cooker Brush 360 Digital Mini
 999          Smart Watch Edge Digital Sense

                                          Description  \
 0             Consumer approach woman us those star.
 1    Point suggest easy money operation could white.
 2                           Reach husband education.
 3              Always choose school poor table main.
 4            Worry put discuss easy back too career.
 ..                                               ...
 995            Piece the fight near never once bank.
 996                 Apply drive outside reach apply.
 997              Line cup course student each about.
 998      History feel worry painting only power bad.
 999                           Pay image either rest.

                             Brand                Category  Price Currency  \
 0                     Bradford-Yu      Kitchen Appliances     74      USD
 1                   Douglas Group       Fitness Equipment    510      USD
 2                   Landry-Austin  Beauty & Personal Care    254      USD
 3         Odom, Norton and Foster                  Makeup     69      USD
 4    Fowler, Mendoza and Mcdaniel              Automotive    525      USD
 ..                            ...                     ...    ...      ...
 995                 Huffman Group            Toys & Games    903      USD
 996                Woodward Group            Toys & Games      8      USD
 997                Ramos-Cardenas  Beauty & Personal Care    615      USD
 998                 Hooper-Bender          Men's Clothing    811      USD
 999                    Campos Inc      Kitchen Appliances    867      USD

      Stock            EAN             Color         Size   Availability  \
 0      139  8619793560985            Orchid       Medium      backorder
 1      351  3057216124300    MediumSeaGreen        Small      backorder
 2      409  9825254410556          Lavender          XXL      pre_order
 3      119  9490814777808              Pink           XL       in_stock
 4      727  4726650403799        LightCoral           XL       in_stock
 ..     ...            ...               ...          ...            ...
 995    737  8227581307423  MediumAquaMarine           XL  limited_stock
 996    330   522633507294     PaleVioletRed       Medium   out_of_stock
 997    630  1892829625606     PaleVioletRed  Extra Large      pre_order
 998    566  1683591150065        LightGreen            S       in_stock
 999    769  8697154897673         Gainsboro     50x70 cm  limited_stock

      Internal ID
 0             38
 1             27
 2              2
 3             94
 4             95
 ..           ...
 995           33
 996            9
 997            4
 998           65
 999           10

 [1000 rows x 12 columns],)

In [9]:
# Remove duplicates & irrelevant columns
df = df.drop_duplicates().drop(columns=["Name", "Index"])

In [10]:
# Check unique value
df['Brand'].unique()

array(['Bradford-Yu', 'Douglas Group', 'Landry-Austin',
       'Odom, Norton and Foster', 'Fowler, Mendoza and Mcdaniel',
       'Burton-Gould', 'Soto, Raymond and Doyle',
       'Padilla, Dunn and Pruitt', 'Hughes and Sons', 'Mcbride-Wyatt',
       'Wilkins, Horne and Farrell', 'Miranda, Lucero and Blevins',
       'Marshall Group', 'Tanner LLC', 'Mathews and Sons',
       'Stephenson PLC', 'Leonard LLC', 'Montes, Hickman and Stout',
       'Matthews Ltd', 'Contreras-Bonilla', 'Greene-Ayers', 'Hanna Group',
       'Quinn-Fields', 'Livingston-Steele',
       'Pearson, Hubbard and Woodward', 'Zavala, Pugh and Wiley',
       'Mcfarland-Buck', 'Kirby and Sons', 'Owen, Caldwell and Salazar',
       'Montoya Group', 'Franklin, Liu and Evans', 'Harrison Ltd',
       'Kennedy-Weiss', 'Joyce, Mcdonald and Maldonado',
       'Mills, Mendez and Waller', 'Maldonado PLC',
       'Payne, Joseph and Ponce', 'Roman and Sons', 'Duarte Ltd',
       'Rogers Ltd', 'Shaffer, Bowers and Parrish', 'Hartman LLC',
       'Montoya, Barnes and Haley', 'Cowan and Sons',
       'Beltran, Khan and Proctor', 'Mckee Ltd', 'Roth-Maddox',
       'Ware, Singh and Holloway', 'Sellers LLC', 'Hess-Daniel',
       'Figueroa-Bowen', 'Garcia, Salazar and Roberson',
       'Price, Ford and Shaw', 'Pena-Schultz', 'Burns-Chavez',
       'Dudley-Johnson', 'Bonilla, Robbins and Hayes', 'Merritt-Maddox',
       'Beasley-Valdez', 'Goodwin LLC', 'Stephens-Keller', 'Jackson-Wall',
       'Mack, Morris and Wall', 'Armstrong-Ramirez', 'Owen Ltd',
       'Nash, Newton and Hodge', 'Finley, Rush and Hawkins',
       'Mcmillan, Robertson and Norris', 'Hebert-Costa',
       'Gordon, Peck and Hurley', 'Santana Inc', 'Shea-Wang',
       'Richards-Hess', 'Calderon PLC', 'Spencer Group', 'Cochran-Burton',
       'Roth-Bates', 'Frost-Richmond', 'Joseph-Chan', 'Foley and Sons',
       'Patrick Group', 'Mcknight, Rosales and Valencia',
       'Burton-Matthews', 'Chung Ltd', 'Dickson-Vega',
       'Christian and Sons', 'Faulkner, Daugherty and Molina',
       'Vincent Group', 'Huff-Morrow', 'Webb-Roman',
       'Duarte, Cisneros and Fitzpatrick', 'Ochoa and Sons',
       'Mcgrath PLC', 'Huber, Clark and Griffith', 'Silva and Sons',
       'Pham-Erickson', 'Barr-Riley', 'Sutton Group', 'Reese-Cox',
       'Wong-Perez', 'Gaines-Schneider', 'Ho, Lang and Shannon',
       'Raymond Ltd', 'Ramirez, Dean and Mueller', 'Mills Group',
       'Hayden, Woodward and Barton', 'Cantrell, Welch and Trevino',
       'Flowers-Werner', 'Olson-Mills', 'Lynn, Figueroa and Craig',
       'Nash-Hughes', 'Riggs-Edwards', 'Schroeder Inc', 'Mcclain-Simpson',
       'Lynn, Simpson and Mcmillan', 'Walker-Woods', 'Kramer PLC',
       'Glover, James and Booker', 'Flynn LLC', 'Oliver PLC',
       'Whitehead PLC', 'Vega-Fernandez', 'Gray Inc', 'Osborne-Rivera',
       'Bush, Archer and Hurley', 'Roach and Sons', 'Lang-Santana',
       'Shaw-Chung', 'Hughes, Melendez and Trevino', 'Becker and Sons',
       'Harper Inc', 'Underwood, Ingram and Gregory', 'Carey LLC',
       'Gentry LLC', 'Allen, Maxwell and Barnett', 'Stokes and Sons',
       'Dougherty LLC', 'Yoder-Hensley', 'Lester-Ross', 'Campos-Chan',
       'Pacheco PLC', 'Sanford, Paul and Byrd',
       'Cunningham, Day and Miller', 'Moreno-Madden',
       'Walton, Marshall and Black', 'Acevedo-Richard', 'Hull LLC',
       'Hopkins PLC', 'Lawson, Bass and Francis',
       'White, Daugherty and Hunt', 'Christensen and Sons', 'Mcclure Inc',
       'Cunningham Group', 'Perez, Alvarez and Gordon', 'Lee Ltd',
       'Cortez, Leach and Raymond', 'Roberson LLC',
       'Huerta, Cummings and Cross', 'Shelton-Faulkner', 'Salas-Bates',
       'Henderson, Bautista and Irwin', 'Bowers-Moreno',
       'Spears, Odom and Bennett', 'Berry, Lowery and Mccann',
       'Bridges Ltd', 'Long, House and Cannon', 'Wang Group',
       'French Group', 'West and Sons', 'Krause-Ramos', 'Price LLC',
       'Chavez-Dawson', 'Benson LLC', 'Villarreal and Sons', 'Todd Group',
       'Wagner, Rangel and Morton', 'Guzman-Leach',
       'Hart, Mercer and Clayton', 'Mays and Sons', 'Oconnell PLC',
       'Fowler-Williams', 'Murray-Petersen', 'Gates-Riggs',
       'Gaines-Pruitt', 'Wall, Morrison and Hurley', 'Sawyer Inc',
       'Wood-Juarez', 'Henderson, Dunn and Bradshaw',
       'Lynch, Ballard and Garrison', 'Davenport, Vazquez and Peters',
       'Gregory, Stanton and Dominguez', 'Nixon LLC',
       'Russell, Newton and Mcgee', 'Daniels-Pearson', 'Webster-Delacruz',
       'Matthews-Baker', 'Henderson LLC', 'Jackson PLC', 'Meadows LLC',
       'Hurst-Blevins', 'Whitaker, Davenport and Esparza', 'Hunt Ltd',
       'Wallace Group', 'Gregory, Macias and Yang', 'Nelson LLC',
       'Velasquez PLC', 'Obrien, Lucero and Krause', 'Ford-Mayer',
       'Lang LLC', 'Costa LLC', 'Mccarthy-Spears', 'Stuart-Trevino',
       'Pace and Sons', 'Boyer-Fleming', 'Ali LLC',
       'Schmitt, Fields and Marquez', 'Brady-David', 'Johnston and Sons',
       'Dixon-Santana', 'Hogan-Carson', 'Baldwin-Schneider',
       'Krause, Bass and Horn', 'Washington Ltd', 'Lozano Inc',
       'Valencia, Tanner and Sosa', 'Li Ltd', 'Owens and Sons',
       'Sherman, Shepherd and Cunningham', 'Hardin-Espinoza',
       'Weeks, Jensen and Andrade', 'Sutton PLC', 'Simon-Werner',
       'Gould, Mays and Clayton', 'Odonnell-Butler', 'Santiago-Chapman',
       'Sherman Group', 'Fox LLC', 'Warner-Hodges', 'Forbes-Mendoza',
       'Goodwin-Sanchez', 'Patton-Choi', 'Holloway, Cohen and Houston',
       'Malone, Bowman and Holland', 'Villegas, Ford and Mccoy',
       'Spears-Saunders', 'George, Gillespie and Mcclure',
       'Duncan, Gonzales and Watkins', 'Griffith-Rios', 'Barajas-Vasquez',
       'Cunningham, Harding and Ruiz', 'Yates, Lewis and Dudley',
       'Griffin and Sons', 'Briggs-Krause', 'Pena-Singleton',
       'Snow, Cobb and Rosales', 'Yates Group', 'Guerrero-Huff',
       'Park, Greer and Stewart', 'Jenkins, Lester and Rios',
       'Porter-Chavez', 'Abbott-Foster', 'Barron-Shea', 'Reilly PLC',
       'Mcmillan, Russell and Weber', 'Elliott, Woodward and Short',
       'Shepherd and Sons', 'Charles-Glass', 'Bright-Mcknight',
       'Fry, Oneal and Montes', 'Garner LLC', 'Arnold Group', 'Cain PLC',
       'Boyle-Guerra', 'Acosta, Cortez and Phelps',
       'Trevino, Wang and Lam', 'Mccall-Lynn', 'Orozco, Nguyen and Miles',
       'Guzman, Ayers and Trujillo', 'Olsen, Tanner and Mccormick',
       'Brock-Owen', 'Morgan-Cisneros', 'Wise, Barry and Proctor',
       'Singh-Estrada', 'Rodriguez PLC', 'Stanley and Sons',
       'Goodwin, Wolfe and Jenkins', 'Strickland, Larson and York',
       'Riggs Inc', 'Rocha-Bright', 'Donaldson and Sons',
       'Aguilar, Stephens and Yates', 'Ware PLC', 'Lane-Kennedy',
       'Ochoa Ltd', 'Orr Ltd', 'Walsh, Shaffer and Hahn', 'Ramirez-Terry',
       'Rogers, Bradley and Buchanan', 'Landry, Blankenship and Harrison',
       'Kaufman-Nash', 'Mccormick Inc', 'Ferguson, Mcgrath and Logan',
       'Thomas, Cannon and Weber', 'Prince Ltd', 'Fitzpatrick-Stark',
       'Espinoza-Anderson', 'Cunningham Ltd', 'Quinn-Collins',
       'Leblanc, Manning and Stout', 'Simpson-Ross', 'Washington Group',
       'Rasmussen-Pollard', 'Spencer-Black', 'Bradshaw-Garrison',
       'Gill-Ochoa', 'Combs-Briggs', 'Reeves, Valenzuela and Zavala',
       'Briggs, Goodwin and Fisher', 'Higgins-Leon', 'Cochran-Rich',
       'Chang, Christensen and Cain', 'Cardenas Inc', 'Weiss-Lyons',
       'Hopkins-Barrett', 'Hampton Inc',
       'Wilkerson, Christensen and Baxter', 'Small Inc', 'Beasley PLC',
       'Schroeder, Hill and Anthony', 'Owen, Joyce and Mcclain',
       'Cannon Ltd', 'Nolan-Lam', 'Holder-Downs', 'Fry-Sexton',
       'Sanders PLC', 'Lucero, Swanson and Murray', 'Lambert LLC',
       'Erickson Inc', 'Joyce Ltd', 'Mckenzie, Ayala and Griffith',
       'Collier LLC', 'Spears Inc', 'Elliott, Howell and Baldwin',
       'Bennett-Hebert', 'Joyce Inc', 'Sloan-Curry',
       'Haas, Bowman and Bass', 'Brandt-Cherry', 'Singh Inc',
       'Cline, Schneider and Ramirez', 'Gilmore-Wells',
       'Owens, Preston and Garza', 'Bentley, Bush and Gilbert',
       'Huffman, Hobbs and Flowers', 'Bolton, Sandoval and Decker',
       'Hanson-West', 'Briggs-Hendricks', 'Chase Ltd', 'Nielsen Ltd',
       'Calderon Group', 'Thornton, Payne and Waters', 'Mooney-Olsen',
       'Mata-Norman', 'Hughes-Rocha', 'Brown Group', 'Moreno PLC',
       'Francis-Johns', 'Stevens, Barton and Hull', 'Thornton-Moyer',
       'Zuniga, Townsend and Huber', 'Day-Noble', 'Dean Ltd',
       'Jarvis, Owen and Downs', 'Chaney-Gentry', 'Cohen, Long and Bauer',
       'Valdez-Vincent', 'Olsen Inc', 'Rivas, Tucker and Humphrey',
       'Silva Inc', 'Lucero-Klein', 'Pearson-Browning',
       'Berg, Dillon and Mueller', 'Duncan-Hayes',
       'Orr, Carr and Williams', 'Short Ltd', 'May and Sons',
       'Fitzgerald Group', 'Monroe PLC', 'Lin, Casey and Allison',
       'Eaton PLC', 'Thomas-Downs', 'Mccarty, Kelly and Tate',
       'Oconnell, Savage and Dougherty', 'Jackson, Shaffer and Garner',
       'White-Herman', 'Bond Ltd', 'Everett Ltd', 'Booth-Bernard',
       'Goodman, Campos and Daniels', 'Travis-Greer', 'Tate-Villa',
       'Kirk Group', 'Mckinney-Huynh', 'Hensley, Hawkins and Gregory',
       'Fischer-Chandler', 'May-Shepherd', 'Rivas, Huffman and Mason',
       'Hunter PLC', 'Pennington and Sons', 'Brock Inc', 'Banks-Dyer',
       'Diaz Group', 'Pittman-Padilla', 'Duke Group',
       'Miller, Harrington and Blanchard', 'Wilkins Inc', 'Evans LLC',
       'Campos-Mcdonald', 'Fischer-Moran', 'Gallegos-Schroeder',
       'Decker, Vasquez and Cervantes', 'Little-Hamilton',
       'Yates, Shelton and Henry', 'Aguilar-Banks', 'Trevino Inc',
       'Huerta-Holder', 'Weeks-Flynn', 'Hansen, Stein and Park',
       'Morrow and Sons', 'Curry Ltd', 'Booker-Sexton', 'Saunders Group',
       'Morales-Krause', 'Atkinson Inc', 'Greer Inc',
       'Walton, Lawson and Gaines', 'Lang-Coleman', 'Spence-Kim',
       'Fox-Weaver', 'Berger, Nash and Flowers', 'Randolph-James',
       'Kirk, Erickson and Gomez', 'Simmons Group', 'Ochoa LLC',
       'Cordova, York and Fry', 'Koch, Floyd and Brewer',
       'Farmer-Ferguson', 'Pollard-Riley', 'Flowers, Santos and Vega',
       'Knox-Santana', 'Bruce Group', 'Jensen-Orr', 'Pierce-Medina',
       'Preston, Lamb and Nunez', 'Crosby, Fitzpatrick and Lane',
       'Deleon, Hubbard and Joseph', 'Wiggins-Johnson', 'Banks PLC',
       'Boone, Velazquez and Hunt', 'Zavala Group', 'Cabrera-Whitaker',
       'Cabrera-Zamora', 'Perez Ltd', 'Knox Inc', 'Rodgers Group',
       'Shea-Guzman', 'Lara Group', 'Massey, Stephenson and Huff',
       'Bond-Gillespie', 'Durham-Harmon', 'Larson, Mann and Guerra',
       'Giles LLC', 'Logan, Vega and Haynes', 'Chase-Reynolds',
       'Houston, Kennedy and Conway', 'Krueger Group', 'Boyd Ltd',
       'Cabrera-Barber', 'Lucas Inc', 'Gilbert-Rangel', 'Collier Inc',
       'Fox-Stone', 'Sullivan, Benton and Howe', 'Andrews-Mcgee',
       'Malone and Sons', 'Benjamin and Sons', 'Osborne, Ford and Butler',
       'Mckenzie-Hensley', 'Francis-Novak', 'Case, Buchanan and Kelly',
       'Gonzales and Sons', 'Le-Fuller', 'Munoz, Jensen and Combs',
       'Blevins, Arias and Choi', 'Lucas-Vance', 'Murray Group',
       'Dunn PLC', 'Tanner PLC', 'Haynes, Decker and Meadows',
       'Lawson-Mullen', 'Meyers, Schwartz and Mcclure',
       'Romero, Krueger and Ferrell', 'Terry, Murray and Morse',
       'Huff-Obrien', 'Wang, Vaughn and Wilson',
       'Hensley, Richard and Gutierrez', 'Li, Baldwin and Watts',
       'Cross, Shannon and Page', 'Vasquez, Graham and Rangel',
       'Bennett, Ingram and Gordon', 'Gray, Raymond and Morrison',
       'Sanders, Figueroa and Mcclain', 'Singh, Morgan and Houston',
       'Larsen-Castro', 'Whitaker Group', 'Barron-Benjamin',
       'Winters Ltd', 'Proctor-Short', 'Ortiz, Merritt and Sanford',
       'King and Sons', 'Le-Barron', 'Downs-Wood',
       'Duffy, Knapp and Orozco', 'Shea LLC', 'Dominguez-Weiss',
       'Daniels-Robertson', 'Weber Group', 'Nolan Inc',
       'Compton, Costa and Davila', 'Mathis Ltd',
       'Mccormick, Franco and Brandt', 'Carroll-Browning', 'Hays Ltd',
       'James, Barker and Booker', 'Underwood-Cox',
       'Lam, Howard and Page', 'Thomas-Dyer', 'Duran-Cole',
       'Price, Mueller and Yates', 'Arellano PLC', 'Novak-Rose',
       'Holmes, Gibbs and Shields', 'Fletcher PLC', 'Vang-Jacobs',
       'Vance PLC', 'Bond PLC', 'Page-Bauer', 'Calderon, Blake and Cline',
       'Fitzpatrick Group', 'Dawson-Rivas', 'Rios PLC', 'Wheeler PLC',
       'Meza-Banks', 'Byrd and Sons', 'Hull, Baldwin and Weber',
       'Lutz, Oconnell and Moody', 'Wheeler Ltd', 'Haney Ltd',
       'Phelps, Kline and Sawyer', 'Matthews, Farrell and Francis',
       'Melendez-Potts', 'Pittman Inc', 'Cain, Sparks and Cooke',
       'Marks-Schaefer', 'Montgomery Group', 'Chen, Hatfield and Barnes',
       'Snow, Thompson and Delacruz', 'Gentry-Mcmillan', 'Rojas-Hendrix',
       'Harmon-Foster', 'Terrell, Cuevas and Rose', 'Morales-Harrington',
       'Sawyer-Mckay', 'Duarte-Nielsen', 'Rios, Duarte and Harris',
       'Mccoy, Turner and Conrad', 'Banks, Ritter and Gilbert',
       'Gonzalez-Montes', 'Andrade-Gentry', 'Ibarra, Yates and West',
       'Mcmillan-Welch', 'Ortiz, Dodson and Cuevas', 'Serrano Inc',
       'Mata, Haley and Sosa', 'Dunn-Whitney', 'Nunez-Dyer',
       'Bond, Carpenter and Clements', 'Reyes Inc', 'Booth-Gamble',
       'Carrillo Inc', 'Fry LLC', 'Sims-Barajas', 'Guzman Inc',
       'Benton-Townsend', 'Doyle, Aguirre and Hill', 'Chandler LLC',
       'Bowen Inc', 'Johnson, Blankenship and Porter', 'Wise and Sons',
       'Shea Ltd', 'Williamson PLC', 'Cuevas, Hardy and Crane',
       'Bailey Group', 'Bradford, Malone and Mclean', 'Orozco Ltd',
       'Dillon-Russo', 'Good, Weiss and Castillo', 'Holden-Gates',
       'Berg, House and Carrillo', 'Daugherty Ltd',
       'Parker, Stevens and Love', 'Avila Inc', 'Stafford LLC',
       'Robertson-Crane', 'Maxwell, Terrell and Rosario',
       'Thompson-Richards', 'Singleton-Tate', 'Pham, Stein and Ortega',
       'Hayes LLC', 'Brock-Sellers', 'Lowe PLC', 'Bridges Inc',
       'Vaughan, Gray and Logan', 'Hampton-Henson', 'Barnett and Sons',
       'Hayden-Shelton', 'Ramos-Riddle', 'Chaney PLC', 'Mann-Yoder',
       'Fletcher, Bates and Stout', 'Romero PLC',
       'Goodwin, Daugherty and Hull', 'Powell Inc', 'Cisneros-Bishop',
       'Lester LLC', 'Mckay, Cooke and Heath', 'Glass PLC', 'Wang-Pope',
       'Rowland LLC', 'Schmitt-Barrera', 'Carney-Reyes', 'Choi LLC',
       'Dawson, Cain and Valencia', 'Shea-Sosa',
       'Velazquez, Pena and Ryan', 'Mcdaniel and Sons', 'Patton-Carr',
       'Cannon, Lambert and Cohen', 'Humphrey Group', 'Gardner-Donaldson',
       'Dyer, Spears and Melton', 'Mora, Jensen and Tapia',
       'Campbell, Garcia and Grimes', 'Goodman, Brock and Roach',
       'Chase-Pugh', 'Torres, Waters and Gallagher', 'Carrillo-Riddle',
       'Melendez-Small', 'Morrow-Hickman', 'Wyatt-Spencer',
       'Ho, Jarvis and Castaneda', 'Chavez, Whitney and Alexander',
       'Klein-Bailey', 'Mccormick, Burnett and Pace', 'Sutton Ltd',
       'Matthews-Winters', 'Velez Group', 'Chan, Christensen and Gentry',
       'Harrington-Simpson', 'Jacobson and Sons', 'Welch PLC',
       'Terrell LLC', 'Carroll LLC', 'Downs Inc', 'Tyler-Burke',
       'Munoz Group', 'Cook, Frey and Ward', 'Durham-Leblanc',
       'Espinoza-Mccullough', 'Hayden and Sons',
       'Oconnor, Carson and Reynolds', 'Cooke LLC',
       'Lam, Henson and Marquez', 'Friedman-Clayton', 'Holland-Jefferson',
       'Mckinney-Mccarty', 'Clarke PLC', 'Grimes-Collier', 'Khan-Ochoa',
       'Spears Group', 'Herring Ltd', 'Koch, Strickland and Stout',
       'Mathis-Lewis', 'Hebert Group', 'Leonard and Sons',
       'Schneider LLC', 'Berry, Middleton and Strong', 'Cobb-Patel',
       'Luna, Blevins and Crane', 'Austin Inc', 'Clements PLC',
       'Reynolds, Martinez and Bradley', 'Brooks-Lin', 'Davis-Bradley',
       'Morse-Combs', 'Day-Dixon', 'Lane LLC', 'Hunter Inc',
       'Ramirez-Pearson', 'Bell, Herring and Boyle', 'Rose-Escobar',
       'May Inc', 'Nichols Inc', 'Bates-Boone', 'Griffith-Hebert',
       'Lucero, Baxter and Diaz', 'Espinoza, Woodard and Burgess',
       'Brooks-Underwood', 'Waller-Whitney',
       'Branch, Stephenson and Forbes', 'Brady-Barnes', 'Moran-Rangel',
       'Mcclain-Caldwell', 'Fisher-Le', 'Pearson-Foley', 'Castaneda-Sims',
       'Garcia-Jones', 'Hayes, Peck and Bridges',
       'Patton, Castro and Williamson', 'Olson, Macdonald and Kemp',
       'Beard Group', 'Larsen-Santos', 'Ross-Gray', 'Keith-Shelton',
       'Michael Inc', 'Ashley-Carroll', 'Roy-Maxwell', 'Thomas Inc',
       'Terrell-Huerta', 'Reyes PLC', 'Lester-Mendez',
       'Mccall, Bass and Dudley', 'Shaw-White', 'Buck-Hoover',
       'Fernandez, Duran and James', 'Gonzalez LLC',
       'Beasley, Miles and Patrick', 'Houston, Barnett and Hernandez',
       'Christensen-Hendrix', 'Mcclure PLC', 'Dunlap, Bonilla and Leon',
       'Brooks-Martin', 'Grant Inc', 'Wolf, Browning and Moody',
       'Wyatt Group', 'Lopez and Sons', 'Aguilar-Rangel',
       'Schneider Group', 'Ayers-Day', 'Glover, Cline and Mann',
       'Armstrong LLC', 'Armstrong, Farley and Dixon', 'Melton Ltd',
       'Carey-Patel', 'Griffith, Nixon and Bass', 'Jenkins-Haney',
       'Hanson-Buchanan', 'Patel, Wyatt and Wolfe', 'Greer-Herring',
       'Bolton-Hensley', 'Hammond-Perkins', 'Mejia-Vincent', 'House PLC',
       'Leblanc PLC', 'Barnett, Lucero and Morales', 'Moreno-Glass',
       'Avila, Stone and Spence', 'Dudley LLC', 'Hernandez-Bowman',
       'Dixon, Ramirez and Williamson', 'Galvan-Wang',
       'Gutierrez, Chandler and Wilson', 'Henderson-Howe', 'Neal-Harding',
       'Jackson, Simpson and Jensen', 'Gonzales-Porter',
       'Roberts-Miranda', 'Pugh, Figueroa and Hill',
       'Mccarthy, Hahn and Colon', 'Key, Gomez and Oneill', 'Bass-Hess',
       'Dillon, Ruiz and Clay', 'Hernandez, Robertson and Hammond',
       'Holt-Parks', 'Wagner-Bright', 'Payne, Mcknight and Michael',
       'Bennett, Marsh and Levine', 'Holmes-Cardenas', 'Curry-Reed',
       'Lane, Blake and Graham', 'Montoya, Adkins and Campos',
       'Deleon, Schroeder and Steele', 'Maldonado and Sons',
       'Krause and Sons', 'Gallegos Group',
       'Fernandez, Mcdonald and Mayer', 'Hobbs-Sanders', 'Bowman-Arnold',
       'Velazquez Group', 'Poole, Browning and Horn', 'Bernard PLC',
       'Curtis-Cantu', 'Hansen, Mcgrath and Barton', 'Lane-Mcneil',
       'Banks and Sons', 'Terry, Palmer and Sexton', 'Finley Ltd',
       'Steele and Sons', 'Cox, Chan and Phelps',
       'Ruiz, Roach and Becker', 'Rush, Andersen and Hunter',
       'Campos PLC', 'Craig and Sons', 'Bass, Chambers and Ellison',
       'Fox Group', 'Holt Inc', 'Houston-Lawson', 'Mcdonald-Fernandez',
       'Rice, Stuart and Monroe', 'Black-Meadows',
       'Clarke, Blake and Fleming', 'Zhang and Sons',
       'Rhodes, Flynn and Townsend', 'Mckinney PLC', 'Leon LLC',
       'Mitchell-Sanchez', 'Nash LLC', 'Webb LLC', 'Kelley-Richard',
       'Brewer, Luna and Rowland', 'Burch Group', 'Lewis-Johnston',
       'Stanton, Molina and Leach', 'Berry-Haley', 'Gomez PLC',
       'Vance-Howe', 'Baldwin Group', 'Potter LLC',
       'Gardner, Dickson and Hernandez', 'Branch, Gallagher and Travis',
       'Nichols Ltd', 'Avila Ltd', 'Hubbard, Fox and Ray', 'Costa-Dillon',
       'Mcconnell PLC', 'Banks, Werner and Barron', 'Waters Inc',
       'Blevins and Sons', 'Cole-Peters', 'Curry, Boyd and Reese',
       'Macias, Griffith and Cooper', 'Thompson, Reeves and Kirk',
       'Swanson, Fuentes and Frederick', 'Bowman-Cortez', 'Mclean Ltd',
       'Kerr, Valenzuela and Dudley', 'Glenn Inc', 'Bradley-Manning',
       'Camacho, Hicks and Fuller', 'Foley-Schroeder', 'Aguilar PLC',
       'Navarro-Mcmahon', 'Gill Group', 'Mitchell, Baird and Hernandez',
       'Baldwin, Watson and Beasley', 'Rowe-Perkins', 'Robertson Inc',

In [11]:
# Check duplicates in 'Sex' column
df["Brand"].duplicated().sum()

np.int64(4)

In [12]:
# check duplicate count
df["Brand"].value_counts()

Brand
Riggs Inc                      2
Christensen and Sons           2
Hampton Inc                    2
Bond PLC                       2
Melendez-Small                 1
                              ..
Collier LLC                    1
Spears Inc                     1
Elliott, Howell and Baldwin    1
Bennett-Hebert                 1
Schroeder, Hill and Anthony    1
Name: count, Length: 996, dtype: int64

In [13]:
# Find rows where multiple columns have same value (Sex + Name)
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/products.csv")
dup_rows = df[df.duplicated(subset=["Brand", "Name"], keep=False)]
print(dup_rows)

Empty DataFrame
Columns: [Index, Name, Description, Brand, Category, Price, Currency, Stock, EAN, Color, Size, Availability, Internal ID]
Index: []

In [14]:
# rename
df1=df.rename(columns={'Internal ID': 'ID'})

In [15]:
# reindex
df2 = df1.reindex(["Name","Description","Brand","Category","Currency","Price","EAN","Color","Size","Stock","Avaibility","ID"])

**MISSING VALUE HANDLING**

In [16]:
df.isna().mean()*100     # % of missing values per column
df.isna().sum()          # Count missing per column

Index           0
Name            0
Description     0
Brand           0
Category        0
Price           0
Currency        0
Stock           0
EAN             0
Color           0
Size            0
Availability    0
Internal ID     0
dtype: int64

In [17]:
# Drop columns with >70% missing values
df = df.dropna(axis=1, thresh=int(0.3*len(df)))

In [18]:
# Drop rows with any missing values
df = df.dropna()

In [19]:
# Numerical: fill with mean
df["Price"].fillna(df["Price"].mean(), inplace=True)
df["Price"].fillna(df["Price"].median(), inplace=True)
df["Price"].fillna(df["Price"].mode()[0], inplace=True)

/tmp/ipython-input-483102530.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mean(), inplace=True)
/tmp/ipython-input-483102530.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].median(), inplace=True)
/tmp/ipython-input-483102530.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Price"].fillna(df["Price"].mode()[0], inplace=True)

**DATA TYPE CORRECTION**

In [20]:
# Converting Strings to Datetime
df["Price"] = pd.to_datetime(df["Price"], errors="coerce")

In [21]:
# Remove commas and convert to numeric
df["Stock"] = pd.to_numeric(df["Stock"])

In [22]:
# Remove currency symbols
df["Currecy"] = df["Currency"].str.replace("USD", "$", regex=True).astype(object)

**Format Standardization**

In [23]:
import pandas as pd
import numpy as np
df9 = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/people.csv")

In [24]:
# 1. Normalize text (lowercase, strip whitespace)
df["Name"] = df["Name"].str.lower().str.strip()

In [25]:
# 2. Standardize Gender (map categorical variants)
df9["Sex"] = df9["Sex"].replace({ "Male": "M","Female": "F"})